feat: add package `read-more`
readr-media/react pull request #118
Opened 2023-01-30 01:28 UTC by ChangRongXuan

## Feature
實作「延伸閱讀」元件：
- 功能
   - 根據螢幕寬度 & 文章數量，自動調整文章排版形式。
   - 點按文章圖片 or 文章標題，可另開分頁至該文章頁面。
   - 文章標題超過特定行數，會截斷並以「...」呈現。
   
- 可調整
   - 標題：標題內容、標題顏色、標題尺寸(font-size)
   - 文章：文章標題顏色、文章標題尺寸(font-size)、文章預設圖片( default-image)
   - 文章資訊 (readMoreData) 

## Detail

### Prop

- readMoreData：包含各文章資訊Object的Array。
   - id: 文章 id。
   - caption: 文章標題。
   - slug: 文章 slug，用於https://www.mirrormedia.mg/story/${slug}/ 作為文章連結。如無，可選擇使用link作為文章連結資料。
   - imageUrl: 文章圖片 URL。
   - alt: 文章圖片替代文字。
   - link: 文章連結。
- title：標題。
- titleColor：標題顏色。
- titleSize：標題尺寸(font-size)。
- captionColor：文章標題顏色。
- captionSize：文章標題尺寸(font-size)。
- defaultImage：文章預設圖片。當readMoreData的imageUrl載入失敗時，則載入預設圖片。

```
import ReadMore from '@readr-media/read-more'

const data = [
  {
    id: 1,
    slug: 'post-slug-01',
    caption: '文章標題01',
    imageUrl: 'https://www.mirrormedia.com.tw',
    alt: '文章敘述01',
    link: 'https://www.mirrormedia.mg',
  }
]

export default function ComponentName() {
  return (
    <ReadMore
      readMoreData={data}
      title="延伸閱讀"
      titleColor="#000000"
      titleSize="16px"
      captionColor="red"
      captionSize="30px"
      defaultImage="default-img.svg"
    />
  )
}
```

## 問題
- 目前`titleSize`和`captionSize`都只能傳入單一數值，但實作上會有需求是依照螢幕寬度做動態調整（ex: 手機版與桌機版的`titleSize`數值可能會不相同），目前還沒想到比較好的處理方式。
- 文章圖片顯示不確定是否需要 loading.gif （參考 @readr-media/react-image)設計概念）

2023-02-02 10:49 UTC, erase2004 requested changes
建議補上 `CHANGELOG.md`，可以使用 [changelog-maker](https://www.npmjs.com/package/changelog-maker) 來生成，補上 `CHANGELOG.md` 後，記得更新 `package.json`，另外，要 publish package 的話，應該需要權限 cc @nickhsine

2023-02-02 10:49 UTC, erase2004 commented on packages/related-post/src/react-components/index.js
> +  useEffect(() => {
把資料檢查放在 useEffect 中會出現一個問題：
錯誤的資料先被拿來組成頁面，等頁面 mount 上去後，才去檢查資料，
合理的操作應該是先檢查資料，再決定是否用資料來組成頁面，
而且檢查到資料有問題，應該終止畫面的組成，避免產生錯誤在頁面上

2023-02-02 10:49 UTC, erase2004 commented on packages/related-post/src/react-components/related-list.js
> +  function RelatedPostImage({ imgSrc, postAmount, alt }) {
`RelatedPostImage` component 雖然沒有被匯出使用，但應該放在 `RelatedLists` component 之外，但依然可以放在該檔案中

2023-02-02 10:49 UTC, erase2004 commented on packages/related-post/src/react-components/related-list.js
> +  display: -webkit-box;
`display: -webkit-box` 和 `-webkit-box-orient` 這兩個應該是 legency 且 non standard 的屬性，應該改用 flexbox 標準的解法

2023-02-02 10:49 UTC, erase2004 commented on packages/related-post/src/react-components/related-list.js
> +const RelatedList = styled.li`
這裡我會用 `RelatedItem` 這樣會出的 `RelatedLists` 就可以改用單數的 `RelatedList`

2023-02-05 09:07 UTC, ChangRongXuan commented on packages/related-post/README.md
> +| titleClassName | String  |     | `""`           | 指定標題className，可用於變更標題樣式。或直接使用預設className：`related-post-title`。                                                                 |
謝提醒 :rofl: 
有在 VSCode 加用 [Pangu-Markdown](https://marketplace.visualstudio.com/items?itemName=xlthu.Pangu-Markdown) 和 [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one#keyboard-shortcuts) 去做格式檢查。（雖然遺產看起來也只能留給貓了 :cat2: ）

2023-02-05 09:27 UTC, ChangRongXuan commented on packages/related-post/README.md
> +$ npm run build
謝提醒！已補上。

2023-02-05 14:13 UTC, ChangRongXuan commented on packages/related-post/dev/entry.js
> +/**
感謝指正！會改成將 `Post` 放在 `src/typedef.js` 作管理，
修正 `props.relatedData` 為 `@param {Post[]} `。

2023-02-05 14:17 UTC, ChangRongXuan commented on packages/related-post/src/react-components/index.js
> + *  @typedef {Array<Object>} Post
感謝指正！會改為將 `Post` 放在 `src/typedef.js` 作管理。

2023-02-05 14:38 UTC, ChangRongXuan commented on packages/related-post/src/react-components/index.js
> +            postAmount={relatedData.length}
了解，當初會獨立把 `postAmount` 拉出來，是想說比較方便閱讀( 但看起來好像沒這個效果XD 反而會比較難懂（？ :thinking: )
會改為以 `relatedData.length` 呈現。

2023-02-05 14:43 UTC, ChangRongXuan commented on packages/related-post/src/react-components/related-list.js
> +  function RelatedPostImage({ imgSrc, postAmount, alt }) {
了解，感謝指正！:raised_hands:
會改成拉出到 `export default function RelatedLists（）` 之前。

2023-02-05 14:55 UTC, ChangRongXuan commented on packages/related-post/src/react-components/related-list.js
> +const RelatedList = styled.li`
感謝建議 > < ! 發現複數型態在命名上真的會稍微干擾.... 已修正！

2023-02-05 15:32 UTC, ChangRongXuan commented on packages/related-post/src/react-components/index.js
> +      <Title className={`related-post-title ${titleClassName}`}>{title}</Title>
感謝建議！
目前是調整成把預設的 className，當作 `props.titleClassName` & `props.captionName` 的 default value。
當使用者沒有傳入指定 className，就會自動代入 default className。

測試了一下發現這樣的寫法，好像可以避開上面提到的程式碼易讀性問題，同時維持原有功能。

```
export default function RelatedPost({
  ......
  titleClassName = 'related-post-title',
  captionClassName = 'related-post-caption',
}) 
  ```

2023-02-05 16:57 UTC, ChangRongXuan commented on packages/related-post/src/react-components/related-list.js
> +  display: -webkit-box;
這一個修改上小卡關：（週一會找時間口頭請教！）
如果要避開使用 `-webkit-box`，寫法上會改成使用 `text-overflow: ellipsis`，
但目前只能試出單行成功的狀況，如果是要多行但又能 `ellipsis`，
目前看到的例子，都還是會回頭去使用 `display: -webkit-box`。
```
PostCaption {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  display: block;
  line-height: 1.2em; /* Set the line height based on the font size */
  height: 3.6em; /* Set the height based on the font size and line height */
}
```
<img width="679" alt="截圖 2023-02-06 上午12 56 53" src="https://user-images.githubusercontent.com/104489150/216833094-22aae2d3-66f3-4a3c-94c6-a86d390e4113.png">

2023-02-05 17:40 UTC, ChangRongXuan commented on packages/related-post/src/react-components/index.js
> +  useEffect(() => {
謝指正！目前調整：
(1) 將 `try/catch` 改爲在 component render 前執行。
(2) 去掉 `printLogInDevMode`，直接透過 `props.debugMode` 當作是否顯示 error message 的條件。

```
  try {
    //check whether `relatedData` is empty.
    //if `relatedData` is empty, show error message.
    if (relatedData.length === 0 && debugMode) {
      console.log(`ERROR: props.relatedData has no data`)
    }

    //check each Object in `relatedData` has `caption`.
    //if some Object in `relatedData` lose `caption`, show error message.
    const checkEmptyCaption = (element) => element.caption !== undefined
    if (relatedData.every(checkEmptyCaption) && debugMode) {
      console.log(`ERROR: caption has no data`)
    }
  } catch (err) {
    console.log(err)
  }
```

2023-02-06 07:12 UTC, ChangRongXuan commented on packages/related-post/src/react-components/related-list.js
> +  display: -webkit-box;
2/6 update: 
因 `text-overflow: ellipsis` 測試上無法在多行狀況下使用，
先暫時保留 `display: -webkit-box` 和 `-webkit-box-orient` 寫法。

2023-02-07 12:54 UTC, ChangRongXuan commented
調整
-
- 文件
   - 新增 `CHANGELOG.md` 。
   - 調整 `README.md` 格式 ＆ `Markdown` 內圖片格式。

- 設定 
   - 考慮到 `related-post` 套件使用上只需要 `/lib`（ ESmodule 轉換為 commonJS ），不需生成 `/dist` 靜態檔案資源。
   - 因此移除 `MakeFile` / `README.md` / `webpack.config.js` 中有關  `build-dist` 的相關設定。
   - 筆記：`webpack.config.js` 在此套件中的功能為讓使用者可透過 `yarn dev` 查看 `dev` 中的範例檔案（`index.html`)。

- JSDoc 
   - 新增 `src/typedef.js` 統一管理套件中的 `typedef` 。
   - 修正 `number` / `string` 以及 `Post[]`用法。

- 其他
   - 新增 `relatedData` 的 try / catch。
   - 將預設的 `title/caption className` 直接設定為 `props` 的 default value，當使用者傳入指定 `className`，則該指定`className`會直接取代套件預設`className`。

2023-02-08 04:43 UTC, erase2004 approved these changes
大致 OK，提到的部份如果有要再修改，可以修改之後再轉為 review request 👏

2023-02-08 04:43 UTC, erase2004 commented on packages/related-post/CHANGELOG.md
> +* \[[`a666446565`](https://github.com/readr-media/related-post/commit/a666446565)] - fix(related-post): relatedData error handle (Xuan)
可以參考 `@readr-media/react-feedback` 的 [CHANGELOG](https://github.com/readr-media/react/blob/main/packages/feedback/CHANGELOG.md) 格式，
手動補上 package 名稱、更新日期、版本資訊、更新內容總結區塊等。

2023-02-08 04:43 UTC, erase2004 commented on packages/related-post/README.md
> +![text](https://github.com/ChangRongXuan/react/blob/read-more/packages/related-post/related-post-example.png)
`![說明文字](./related-post-example.png)`
使用上述內容進行替換會更好，畢竟圖片在 repo 中就有，不用特地外連，
另外，說明文字請自行替換貼切的內容

2023-02-08 04:43 UTC, erase2004 commented on packages/related-post/CHANGELOG.md
> +* \[[`a666446565`](https://github.com/readr-media/related-post/commit/a666446565)] - fix(related-post): relatedData error handle (Xuan)
btw, CHANGELOG 中的版本資訊要和 `package.json` 中的 `version` 同步

2023-02-08 04:43 UTC, erase2004 commented on packages/related-post/src/react-components/index.js
> +  try {
Ln. 74 ~ Ln. 89 包成一個 `checkXXXX` or `isValidXXXX` 的 function，回傳值為 boolean type，
然後給 Ln. 94 取代 `relatedData?.length !== 0` 使用，
這樣更能夠聯繫這一段檢查和元件顯示控制的關係

2023-02-19 15:02 UTC, ChangRongXuan commented on packages/related-post/CHANGELOG.md
> +* \[[`a666446565`](https://github.com/readr-media/related-post/commit/a666446565)] - fix(related-post): relatedData error handle (Xuan)
感謝提醒 :crab:，目前因為套件為初版(initial version)，所以統一修改為：
 
## Version 1.0.0

This is initial version.

後續版本如果有 bump up，會參考 `@readr-media/react-feedback` 的格式加上其他資訊。

2023-02-19 15:11 UTC, ChangRongXuan commented
調整
-

- 重構： 
   - package 名稱改為 `mirrormedia-project`，作為 mirrormedia（鏡電視/鏡週刊）Site/Project 共用元件庫。
   - 元件包含：`MirrorMediaLogo`, `MirrorTVLogo`, `ShareButton`, `RelatedPost`。

- 文件：修正 `CHANGELOG.md` ＆ `README.md` 中 image-link 格式。 
- 其他：修正 `RelatedPost` 中 try/catch（Ln. 74 ~ Ln. 89）寫法 。

2023-02-19 19:35 UTC, ChangRongXuan commented on packages/related-post/src/react-components/index.js
> +  try {
感謝建議 :crab: 不好意思稍晚回覆（the commit 97e1783714787d5200c5f5d43a376a693024ac93 solved this issue）

### 調整：
- 新增函式 `isDataEmpty()`，將 `try/catch` 改放於函式中，並判斷 `relatedData.length`，如果 data 為空陣列或 undefined，則回傳 `false`，讓整個 `RelatedPost` 元件不會顯示於畫面上。
- try/catch 判斷：
   - 條件一：如 `relatedData` 為空陣列或 undefined，則 throw error。
   - 條件二：如 `relatedData.length !==0 `，則進一步判斷是否每個 Object 皆含有 required 的 `caption` 資訊，如無則 throw error。

- 移除 `debugMode`：考量到此元件錯誤狀況較單一，因此移除`debugMode`。當 required 的 `relatedData` 和 `caption` 資訊有遺漏，一律顯示錯誤訊息，提醒使用者修改。


```
  function isDataEmpty(data) {
    try {
      if (!data?.length)
        throw `Error: The 'relatedData' array is empty or undefined.`
      if (
        !data?.every(
          (obj) => obj.hasOwnProperty('caption') && obj['caption'] !== ''
        )
      )
        throw `Error: Not all objects in 'relatedData' have the key 'caption'`
    } catch (err) {
      console.log(err)
    }

    return data?.length !== 0
  }
  ```

2023-02-20 03:09 UTC, nickhsine commented
Suggestion:
`mirrormedia` 是舊的命名規則，為了避免誤會，新的 convention 是 `mirror-weekly` 或是 `weekly`，再麻煩調整一下 pkg name 和 variable name。

2023-02-22 03:58 UTC, ChangRongXuan commented
重構
-
原因：
- 考量到 `mirrormedia` 為過去專案上誤用（ 因鏡電視與鏡週刊都隸屬於 `mirrormedia` 下，但過去專案都以`mirrormedia` 指稱鏡週刊，易造成誤會），因此修改掉原 package 名稱，改用 `mirror-weekly` 指稱「鏡週刊」， `mirror-tv` 指稱「鏡電視」。
- 延續在 slack front-end 針對 monorepo 的[共識](https://mirrormedia.slack.com/archives/C3HAC7SKV/p1666164940575259)，跨部門的共用元件一律整理於 `@readr-media/react` 。因此整併 Readr、mirror-tv、mirror-tv 中與靜態專題 `Project` 相關的共用元件為 package `project` 方便管理。

影響：
- 使用者的引用方式需多指定一層元件類別。ex: `import { WeeklyLogo } from '@readr-media/project/weekly`
```
|──  project/          
|  └──src/           
|       └── readr/                    - Readr Site/Project
|          └── readr-logo/            - Readr Logo       
|          └── donate-button/         - 贊助按鈕       
|          └── subscribe-button/      - 訂閱電子報按鈕       
|          └── related-report/        - 相關報導
|  
|       └── weekly/                   - 鏡週刊 Site/Project   
|          └── weekly-logo/            - 鏡週刊 Logo     
|          └── share-button/           - 社群分享按鈕              
|          └── related-post/          - 相關文章
|     
|       └── tv/                       - 鏡電視 Site/Project        
|          └── tv-logo/                - 鏡電視 Logo           
|

2023-02-22 12:42 UTC, erase2004 requested changes
問題過多，且在類似的元件上重複，建議把該 PR 拆成多次的 PR，一個 PR 發一個 component 就好，另外，readr 的 related-report 先 pending，它原先是使用 `RdArticleListCard`，這個在實作 header-general 中有實作了，可能再討論怎麼處理這一塊，避免元件和處理邏輯出現在不同的 repo 底下

2023-02-22 12:42 UTC, erase2004 commented on packages/project/src/weekly/share-button/README.md
> +| size      | String            |      | ' '              | 設定 Button 尺寸高。（ 因寬高比 1:1，因此此數值會同時設定為寬高）                       |
`size` 屬性似乎不是那麼必要，而且不是那麼好用，畢竟只能設定單一尺寸，而且還不能隨著 viewport 更改，
應該保留使用 `className` 去修改就好了

2023-02-22 12:42 UTC, erase2004 commented on packages/project/src/weekly/share-button/react-components/social-icon.js
> +  const [showAlert, setShowAlert] = useState('')
這應該改為 boolean，然後 `<CopyAlert>` 藉由 showAlert 的數值，來 toggle className，而不是在 `<SocialIcon>` 中 toggle <CopyAlert> 的 className

2023-02-22 12:42 UTC, erase2004 commented on packages/project/src/weekly/share-button/react-components/social-icon.js
> +      <a
在 LinkIcon 的情況下，應該不用 target 和 rel 屬性，順道一題，`<button>` 會比 `<a>` 更合適

2023-02-22 12:44 UTC, erase2004 commented
> 問題過多，且在類似的元件上重複，建議把該 PR 拆成多次的 PR，一個 PR 發一個 component 就好，另外，readr 的 related-report 先 pending，它原先是使用 `RdArticleListCard`，這個在實作 header-general 中有實作了，可能再討論怎麼處理這一塊，避免元件和處理邏輯出現在不同的 repo 底下

btw, 沒有看完全部的內容，所以推測還有不少沒被回饋的問題。

2023-02-22 14:46 UTC, erase2004 commented
其實全部 org 特定的 share component，整併到 `packages/project` 這底下似乎不太合理，應該分為 `packages/weekly-components`, `packages/readr-components` 和 `packages/tv-components`，然後個別管理自己的專有 share component，
以降低彼此開發上的耦合
cc @nickhsine 你那邊怎麼看？

2023-02-24 03:10 UTC, ChangRongXuan commented on packages/project/src/readr/readr-logo/react-components/icon.js
> +    </svg>
> 有點好奇 READr logo 有幾種顏色樣式

先回覆這點！目前設計需求是希望顏色有：黑 / 白 / 標準色 (`#444746`, `#ddcf21`) 。

2023-03-01 04:17 UTC, ChangRongXuan commented
2023/03/01 update: 

因共用元件架構有所更動，不同 organization 的專題共用元件將會移至該 org 的 `packages/react-components` 中，`readr-media/react` 將只會存放跨 orgs 皆會使用到的共用元件。[文件](https://paper.dropbox.com/doc/Shared-Component--BzngWMRJervgXY2GSPV9f1RKAg-TGKDjl6ZDKdcgJL4IiTYN)
- Readr(readr-media) 專題共用元件：see [Almisael](https://github.com/readr-media/Almisael) / packages/react-components
- 鏡週刊(mirror-weekly) 專題共用元件：see [Sandalphon](https://github.com/mirror-media/Sandalphon) / packages/react-components
- 鏡電視(mnirror-tv) 專題共用元件：see [Leliel](https://github.com/mirror-media/Leliel) / packages/react-components
- 跨 orgs 共用元件：see [readr-media/react](https://github.com/readr-media/react)

此 PR 已照上述架構，拆分至對應的 orgs 中做處理，故關閉此 PR：
- Readr(readr-media) ：https://github.com/readr-media/Almisael/pull/3
- 鏡週刊(mirror-weekly) ：https://github.com/mirror-media/Sandalphon/pull/7
- 鏡電視(mnirror-tv)：https://github.com/mirror-media/Leliel/pull/37

2023-03-01 04:17 UTC, closed without merging