feat: add `share-button` package
readr-media/react pull request #126
Opened 2023-03-01 05:16 UTC by ChangRongXuan

## 新增
- 新增 `packages/share-button` 。
- 因爲此元件會跨 orgs 同時於 `mirror-weekly` 與 `mirror-tv` 使用，所以放在 readr-media/react 作管理。
- 此 PR 修改自：https://github.com/readr-media/react/pull/118

## 修正
- [#r1114164769](https://github.com/readr-media/react/pull/118/files#r1114164769)：修改 README 圖片連結。
- [#r1114233267](https://github.com/readr-media/react/pull/118/files#r1114233267)：移除 `size` 參數，改為統一透過 className 調整（且FB.Line.Link icon 也會等比放大）
- [#r1114216969](https://github.com/readr-media/react/pull/118/files#r1114216969)：移除 vendor prefix 設定。
- [#r1114219726](https://github.com/readr-media/react/pull/118/files#r1114219726)：移除 `<a>`中的多餘 `cursor:pointer`。
- [#r1114253588](https://github.com/readr-media/react/pull/118/files#r1114253588)：將原先 useState 的 `showAlert` 改為 boolean，作為 toggle className 使用。
- [#r1114257177](https://github.com/readr-media/react/pull/118/files#r1114257177)：修改 `LinkIcon` 為 button，且移除  target 和 rel 屬性。

2023-03-01 07:43 UTC, erase2004 requested changes

2023-03-01 07:43 UTC, erase2004 commented on packages/share-button/src/react-components/social-icon.js
> +    setShowAlert(true)
`showAlert` 為 true 時，是否應避免第二次點擊，
或者把前面的 timeout 給 clear，再次設定新的 timeout，
藉此來避免：
在前面的 setTimeout 行為尚為結束時，再次 setTimeout，
導致第二次點擊顯示時間沒有跟著延長的問題？

2023-03-01 07:43 UTC, erase2004 commented on packages/share-button/src/react-components/copy-alert.js
> +const CopyAlert = styled.div`
因為 `CopyAlert` 在 `IconWrapper` 底下，又 `IconWrapper` 在整個元件的根元素 `div` 底下，現在 `CopyAlert` 會吃到來源根元素的 `cursor: pointer` 效果，導致它即便沒有顯示時，當滑鼠經過時，會有轉為手指的非預期行為，
我建議可以在 CopyAlert 上，調整 CSS 樣式和 `fadeOut` 動畫行為，讓 `<p>` 的尺寸預設為 0，然後，當要顯示時，先把尺寸還原，接著透明度再跟進，最後要消失時，先透明度，接著尺寸變成 0，這樣就可以避免這個問題
這是其中一解法，有其他解法也歡迎提出。

![Snipaste_2023-03-01_14-15-44](https://user-images.githubusercontent.com/1367757/222071191-9f1ba57d-4283-4273-847c-a9fd58b59e6a.png)

2023-03-01 07:43 UTC, erase2004 commented on packages/share-button/src/index.js
> +const ButtonWrapper = styled.div`
`ButtonWrapper` 或許可以考慮用 `<button>` 來實作，這樣對鍵盤操作會更友善，處理起來也會比較簡單

2023-03-01 07:43 UTC, erase2004 commented on packages/share-button/src/react-components/social-icon.js
> +  direction,
`ShareButton` 中有設定預設值了，這裡應該沒必要再設定預設值了？

2023-03-01 07:43 UTC, erase2004 commented on packages/share-button/src/index.js
> +        onClick()
應該檢測 `onClick` 為 function type 時，再去呼叫 `onClick`，不然會跑出不必要的 error

2023-03-01 09:57 UTC, erase2004 commented
補充：麻煩在最上層的 README 中，補上這個 package 的資訊

2023-03-01 13:31 UTC, ChangRongXuan commented on packages/share-button/src/react-components/copy-alert.js
> +const CopyAlert = styled.div`
這個問題剛好在處理 [#r1121278808](https://github.com/readr-media/react/pull/126/files#r1121278808) `<ButtonWrapper>` 的 a11y 鍵盤操作問題時，有一併解決。

### 問題描述
因為 `<SocialIcon/>` 中的 `LinkIcon` 在上次修改中已經改為 `<button>`，所以最外層包住 `LinkIcon` 的 `ButtonWrapper` 沒辦法改為 `<button>`（會報錯顯示 button 內無法包 button）。
### 修改方向
1. 改成透過 `<button>` 包住 `ShareIcon` ，讓其可被鍵盤選取。 `ButtonWrapper` 只作為 `ShareIcon` 、`SocialIcon` 最外層統一控制 icon 大小的 div container。
2. 之前會造成 `CopyAlert` 有 cursor: pointer 的效果，是因為`ButtonWrapper`有相關的 css 設定（原本是為了提示使用者 `ShareIcon` 可被點選），但透過 1. 的修改，`ShareIcon` 會獨立為一個 button，`cursor`、`onClick`、`aria-label` 都會改成掛在該 button 底下，且不會影響到  `CopyAlert` 。
### 備註
改完之後覺得是之前的架構沒有寫的很好。目前的寫法，比較清楚區分`ButtonWrapper`作為 container，裡面包含`ShareIcon`、`SocialIcon`兩個 button group，且各 button 的`cursor`、 `onClick`、`aria-label` 都掛在各 button上、而非與 `ButtonWrapper` 混雜共用的模糊問題。

```
    <ButtonWrapper className={className}>
      <button onClick={...}  aria-label='...' >
        <ShareIcon />
      </button>
      <SocialIcon/>
    </ButtonWrapper>
```

2023-03-01 15:27 UTC, ChangRongXuan commented on packages/share-button/src/react-components/social-icon.js
> +  direction,
感謝指正 :raised_hands:   :raised_hands:
搬移 code 的時候忘記刪掉，已修改！

2023-03-01 16:17 UTC, ChangRongXuan commented
## 修正
- [#r1121278808](https://github.com/readr-media/react/pull/126/files#r1121278808)：重構`ButtonWrapper` html 架構，透過  在 `ShareIcon` 外加`<button>` ，解決 a11y 鍵盤操作問題。（修改細節記錄於：[#r1121734255](https://github.com/readr-media/react/pull/126#discussion_r1121734255))
- [#r1121276710](https://github.com/readr-media/react/pull/126/files#r1121276710)：透過重構 `ButtonWrapper` html 架構，解決 `CopyAlert` 有 `cursor: pointer` 問題。並新增 `user-select:none`，防止 `CopyAlert` 被選取＆滑鼠符號更動。（修改細節記錄於：[#r1121734255](https://github.com/readr-media/react/pull/126#discussion_r1121734255))
- [#r1121205514](https://github.com/readr-media/react/pull/126/files#r1121205514)：移除 `social-icon.js` 中 `props.show` 和 `props.direction` JSDoc 中的多餘預設值。
- [#r1121259349](https://github.com/readr-media/react/pull/126/files#r1121259349)：新增對於 `LinkIcon` 的點擊條件設定以防止連續多次點擊。當 `CopyAlert` 尚未 fadeOut 時，`LinkIcon` 為 disabled，無法被點擊。
- [#r1121203749](https://github.com/readr-media/react/pull/126#discussion_r1121203749)、[#r1121282685](https://github.com/readr-media/react/pull/126#discussion_r1121282685)：新增對於傳入 props 中 `onClick`、`FbClick`、`LineClick`、`LinkClick` 是否為 function 的 typeOf 條件判定。

2023-03-02 04:10 UTC, erase2004 requested changes

2023-03-02 04:10 UTC, erase2004 commented on packages/share-button/src/react-components/social-icon.js
> +    setShowAlert(true)
這樣應該需要一個 button[disabled] 的效果，例如 `cursor: not-allowed` 或 `cursor: none` 之類

2023-03-02 04:10 UTC, erase2004 commented on packages/share-button/src/react-components/copy-alert.js
> +const CopyAlert = styled.div`
主要還是那個區域即便沒有顯示內容時，它依舊在畫面上佔有一部分的空間，想像底下如果有互動元件剛好被蓋到時，那麼這個互動元件就無法被使用者觸發到，因此，需要一些手段，讓該區域在沒有顯示內容時，不會佔用頁面空間 (除了 `display: none` 之外，有其他可以讓該區域不佔用空間的方法)
![Snipaste_2023-03-02_12-07-11](https://user-images.githubusercontent.com/1367757/222328683-7ca71857-46ca-48b3-ad4b-d03af3aa2e12.png)

2023-03-02 15:29 UTC, ChangRongXuan commented on packages/share-button/src/react-components/social-icon.js
> +    setShowAlert(true)
感謝提醒 :crab:   已補上 `> button[disabled] { cursor: not-allowed }`
當 button 無法點擊時鼠標會有相應提示。

2023-03-02 16:07 UTC, ChangRongXuan commented on packages/share-button/src/react-components/copy-alert.js
> +const CopyAlert = styled.div`
了解，不好意思上一版本修改的時候，沒有注意到元件有佔到空間這個問題 > <  以下是目前調整的內容：

### 調整

- 一般狀態：`display: none`，通知框（ `className='copy-alert'` ) 不會在畫面上佔空間 or 出現。
- 點擊後：因 className 會被抽換為 `'animate fadeOut'`，此時的 css 設定為 `display: block`。當 fadeOut 動畫結束後，通知框的 className 會被抽換回 `.copy-alert`，此時回復為 `display:none `狀態。

### 討論
- 目前選擇調整 `display` 是因為：如果是調整 `width` 從 0 -> 正常寬度，在通知框隱藏的狀態下，畫面上還是會有 `<p>`的存在 ; 如果是用 `display: none`的話，在隱藏狀態下才有辦法完全選不到 `<p>`。  
- 但看了一下前面的建議，好像比較不推薦用 `display: none` 處理的感覺（目前兩種方法可以 work，只是會有上述的差異），想好奇問一下原因～（或只是我理解錯誤XD 那這邊先說拍謝 :rofl: ）
 
![IMG_20230302_235754 (1)](https://user-images.githubusercontent.com/104489150/222482597-f2251287-2924-4562-b33a-f0c535c3750f.jpg)

2023-03-02 16:13 UTC, ChangRongXuan commented
## 修正
- [#r1122576152](https://github.com/readr-media/react/pull/126#discussion_r1122576152)：當 `LinkIcon` button disabled 狀態下，新增 `cursor: not-allowed` 滑鼠狀態提示。
- [#r1122578401](https://github.com/readr-media/react/pull/126#discussion_r1122578401)：
   - 調整 `copy-alert` 的 `display` 狀態，避免通知框沒有顯示時，仍佔用畫面空間問題。
   - 詳細修改細節紀錄於 [#r1123347488](https://github.com/readr-media/react/pull/126#discussion_r1123347488)。

2023-03-05 16:18 UTC, erase2004 approved these changes
LGTM 👍

2023-03-05 16:18 UTC, erase2004 commented on packages/share-button/src/react-components/copy-alert.js
> +    z-index: 9999;
nitpick: 使用 `z-index` 的情況下，盡可能描述使用原因

2023-03-06 03:36 UTC, ChangRongXuan commented on packages/share-button/src/react-components/copy-alert.js
> +    z-index: 9999;
已於 `README` 和 `copy-alert.js` 中新增關於 z-index 的補充和註解。
感謝 Tsuki 的 review 和建議 :pray::pray:

2023-03-06 03:36 UTC, merged